typography_spectrum: 0.7966594342142344
color:
  brandStrength: 0.6521513818297535
  lightness: 0.40047936304472387
  saturation: 0.5979734878055751
  rhythmicContrast: 0.3546804382931441
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
github: true
layout_spectrum: 0.4458078546449542
author:
  name: Duane Cunningham
  email: duanecunningham@gmail.com
  url: www.gangsterandgatsby.com
name: gangsterandgatsby
title: Gangster And Gatsby - "The Willy Wonka" Of The Milkshake World!
content: []
description: >-
  Gangster And Gatsby: A destination experience with exclusive dessert menu, the
  world famous "Gangster Shakes", private label coffee and exceptional service!
purpose:
  - type: external
    url: >-
      http://widget.dimmi.com.au/step1?restaurantId=32127&referrerUrl=http%3A%2F%2Ffacebook.com&showHeader=True
    label: >-
      http://widget.dimmi.com.au/step1?restaurantId=32127&referrerUrl=http%3A%2F%2Ffacebook.com&showHeader=True
